export const DIALOGS_LOAD_START = 'DIALOGS_LOAD_START';
export const DIALOGS_LOAD_SUCCESS = 'DIALOGS_LOAD_SUCCESS';
export const DIALOGS_LOAD_ERROR = 'DIALOGS_LOAD_ERROR';
export const DIALOGS_CURRENT_CHANGE = 'DIALOGS_CURRENT_CHANGE';

export const DIALOGS_GET = 'DIALOGS_GET';
